
/*
Auto-generated by CVXPYgen on September 25, 2025 at 21:59:06.
Content: Declarations for Python binding with pybind11.
*/

// User-defined parameters
struct CPG_Params_cpp_t {
    double b_2;
    double c_31;
    double d_3;
    std::array<double, 4> A_31;
    std::array<double, 4> b_3;
    double c_41;
    double d_4;
    std::array<double, 4> A_41;
    std::array<double, 4> b_4;
};

// Flags for updated user-defined parameters
struct CPG_Updated_cpp_t {
    bool b_2;
    bool c_31;
    bool d_3;
    bool A_31;
    bool b_3;
    bool c_41;
    bool d_4;
    bool A_41;
    bool b_4;
};

// Primal solution
struct CPG_Prim_cpp_t {
    std::array<double, 4> x;
};

// Dual solution
struct CPG_Dual_cpp_t {
    std::array<double, 5> d0;
    std::array<double, 2> d1;
    std::array<double, 5> d2;
    std::array<double, 5> d3;
    double d4;
    double d5;
};

// Solver information
struct CPG_Info_cpp_t {
    double obj_val;
    int iter;
    int status;
    double pri_res;
    double dua_res;
    double time;
};

// Solution and solver information
struct CPG_Result_cpp_t {
    CPG_Prim_cpp_t prim;
    CPG_Dual_cpp_t dual;
    CPG_Info_cpp_t info;
};

// Main solve function
CPG_Result_cpp_t solve_cpp(struct CPG_Updated_cpp_t& CPG_Updated_cpp, struct CPG_Params_cpp_t& CPG_Params_cpp);
