
/*
Auto-generated by CVXPYgen on September 25, 2025 at 21:59:06.
Content: Example program for updating parameters, solving, and inspecting the result.
*/

#include <stdio.h>
#include "cpg_workspace.h"
#include "cpg_solve.h"

static int i;

int main(int argc, char *argv[]){

  // Update first entry of every user-defined parameter
  cpg_update_b_2(0.75367356636115956370);
  cpg_update_c_31(0.48438552479633822934);
  cpg_update_d_3(0.96899350370282977263);
  cpg_update_A_31(0, 0.00000000000000000000);
  cpg_update_b_3(0, 0.04513781466362665196);
  cpg_update_c_41(0.72789188298800377996);
  cpg_update_d_4(0.84201941147054648606);
  cpg_update_A_41(0, 0.00000000000000000000);
  cpg_update_b_4(0, 0.64982839199813158260);

  // Solve the problem instance
  cpg_solve();

  // Print objective function value
  printf("obj = %f\n", CPG_Result.info->obj_val);

  // Print primal solution
  for(i=0; i<4; i++) {
    printf("x[%d] = %f\n", i, CPG_Result.prim->x[i]);
  }

  // Print dual solution
  for(i=0; i<5; i++) {
    printf("d0[%d] = %f\n", i, CPG_Result.dual->d0[i]);
  }
  for(i=0; i<2; i++) {
    printf("d1[%d] = %f\n", i, CPG_Result.dual->d1[i]);
  }
  for(i=0; i<5; i++) {
    printf("d2[%d] = %f\n", i, CPG_Result.dual->d2[i]);
  }
  for(i=0; i<5; i++) {
    printf("d3[%d] = %f\n", i, CPG_Result.dual->d3[i]);
  }
  printf("d4 = %f\n", CPG_Result.dual->d4);
  printf("d5 = %f\n", CPG_Result.dual->d5);

  return 0;

}
