
/*
Auto-generated by CVXPYgen on September 25, 2025 at 21:59:06.
Content: Variable definitions.
*/

#include "cpg_workspace.h"

// Vector containing flattened user-defined parameters
cpg_float cpg_params_vec[22] = {
(cpg_float)0.75367356636115956370,
(cpg_float)0.48438552479633822934,
(cpg_float)0.96899350370282977263,
(cpg_float)0.00000000000000000000,
(cpg_float)0.00000000000000000000,
(cpg_float)0.00000000000000000000,
(cpg_float)0.00000000000000000000,
(cpg_float)0.04513781466362665196,
(cpg_float)0.25441145221464200876,
(cpg_float)0.79784091802427836715,
(cpg_float)0.95732389110044013858,
(cpg_float)0.72789188298800377996,
(cpg_float)0.84201941147054648606,
(cpg_float)0.00000000000000000000,
(cpg_float)0.00000000000000000000,
(cpg_float)0.00000000000000000000,
(cpg_float)0.00000000000000000000,
(cpg_float)0.64982839199813158260,
(cpg_float)0.62008491851713898324,
(cpg_float)0.08359122644124217238,
(cpg_float)0.96905572126736638783,
(cpg_float)1.00000000000000000000,
};

// Sparse mappings from user-defined to canonical parameters
cpg_int canon_G_map_i[19] = {
21,
21,
1,
3,
4,
5,
6,
11,
13,
14,
15,
16,
21,
21,
21,
21,
21,
21,
21,
};
cpg_int canon_G_map_p[20] = {
0,
1,
2,
3,
4,
5,
6,
7,
8,
9,
10,
11,
12,
13,
14,
15,
16,
17,
18,
19,
};
cpg_float canon_G_map_x[19] = {
(cpg_float)-1.00000000000000000000,
(cpg_float)-2.00000000000000000000,
(cpg_float)-1.00000000000000000000,
(cpg_float)-1.00000000000000000000,
(cpg_float)-1.00000000000000000000,
(cpg_float)-1.00000000000000000000,
(cpg_float)-1.00000000000000000000,
(cpg_float)-1.00000000000000000000,
(cpg_float)-1.00000000000000000000,
(cpg_float)-1.00000000000000000000,
(cpg_float)-1.00000000000000000000,
(cpg_float)-1.00000000000000000000,
(cpg_float)-1.00000000000000000000,
(cpg_float)-1000.00000000000000000000,
(cpg_float)-0.04287499999999998951,
(cpg_float)-1.00000000000000000000,
(cpg_float)-1000.00000000000000000000,
(cpg_float)-0.04287499999999998951,
(cpg_float)-1.00000000000000000000,
};
cpg_csc canon_G_map = {canon_G_map_p, canon_G_map_i, canon_G_map_x, 19};

cpg_int canon_h_map_i[12] = {
21,
0,
2,
7,
8,
9,
10,
12,
17,
18,
19,
20,
};
cpg_int canon_h_map_p[20] = {
0,
0,
0,
0,
0,
0,
0,
0,
1,
2,
3,
4,
5,
6,
7,
8,
9,
10,
11,
12,
};
cpg_float canon_h_map_x[12] = {
(cpg_float)29.99999000000000037858,
(cpg_float)1.00000000000000000000,
(cpg_float)1.00000000000000000000,
(cpg_float)1.00000000000000000000,
(cpg_float)1.00000000000000000000,
(cpg_float)1.00000000000000000000,
(cpg_float)1.00000000000000000000,
(cpg_float)1.00000000000000000000,
(cpg_float)1.00000000000000000000,
(cpg_float)1.00000000000000000000,
(cpg_float)1.00000000000000000000,
(cpg_float)1.00000000000000000000,
};
cpg_csc canon_h_map = {canon_h_map_p, canon_h_map_i, canon_h_map_x, 12};

// Canonical parameters
cpg_float canon_c[4] = {
(cpg_float)0.00000000000000000000,
(cpg_float)0.00000000000000000000,
(cpg_float)0.00000000000000000000,
(cpg_float)1.00000000000000000000,
};

cpg_float canon_c_conditioning[4] = {
(cpg_float)0.00000000000000000000,
(cpg_float)0.00000000000000000000,
(cpg_float)0.00000000000000000000,
(cpg_float)1.00000000000000000000,
};

cpg_int canon_G_i[19] = {
3,
8,
9,
10,
11,
12,
13,
14,
15,
16,
17,
18,
0,
4,
9,
1,
5,
14,
2,
};
cpg_int canon_G_p[5] = {
0,
12,
15,
18,
19,
};
cpg_float canon_G_x[19] = {
(cpg_float)-1.00000000000000000000,
(cpg_float)-2.00000000000000000000,
(cpg_float)-0.48438552479633822934,
(cpg_float)0.00000000000000000000,
(cpg_float)0.00000000000000000000,
(cpg_float)0.00000000000000000000,
(cpg_float)0.00000000000000000000,
(cpg_float)-0.72789188298800377996,
(cpg_float)0.00000000000000000000,
(cpg_float)0.00000000000000000000,
(cpg_float)0.00000000000000000000,
(cpg_float)0.00000000000000000000,
(cpg_float)-1.00000000000000000000,
(cpg_float)-1000.00000000000000000000,
(cpg_float)-0.04287499999999998951,
(cpg_float)-1.00000000000000000000,
(cpg_float)-1000.00000000000000000000,
(cpg_float)-0.04287499999999998951,
(cpg_float)-1.00000000000000000000,
};
cpg_csc canon_G = {canon_G_p, canon_G_i, canon_G_x, 19};

cpg_int canon_G_conditioning_i[19] = {
3,
8,
9,
10,
11,
12,
13,
14,
15,
16,
17,
18,
0,
4,
9,
1,
5,
14,
2,
};
cpg_int canon_G_conditioning_p[5] = {
0,
12,
15,
18,
19,
};
cpg_float canon_G_conditioning_x[19] = {
(cpg_float)-1.00000000000000000000,
(cpg_float)-2.00000000000000000000,
(cpg_float)-0.48438552479633822934,
(cpg_float)0.00000000000000000000,
(cpg_float)0.00000000000000000000,
(cpg_float)0.00000000000000000000,
(cpg_float)0.00000000000000000000,
(cpg_float)-0.72789188298800377996,
(cpg_float)0.00000000000000000000,
(cpg_float)0.00000000000000000000,
(cpg_float)0.00000000000000000000,
(cpg_float)0.00000000000000000000,
(cpg_float)-1.00000000000000000000,
(cpg_float)-1000.00000000000000000000,
(cpg_float)-0.04287499999999998951,
(cpg_float)-1.00000000000000000000,
(cpg_float)-1000.00000000000000000000,
(cpg_float)-0.04287499999999998951,
(cpg_float)-1.00000000000000000000,
};
cpg_csc canon_G_conditioning = {canon_G_conditioning_p, canon_G_conditioning_i, canon_G_conditioning_x, 19};

cpg_float canon_h[19] = {
(cpg_float)0.00000000000000000000,
(cpg_float)0.00000000000000000000,
(cpg_float)0.00000000000000000000,
(cpg_float)0.00000000000000000000,
(cpg_float)0.00000000000000000000,
(cpg_float)0.00000000000000000000,
(cpg_float)0.00000000000000000000,
(cpg_float)29.99999000000000037858,
(cpg_float)0.75367356636115956370,
(cpg_float)0.96899350370282977263,
(cpg_float)0.04513781466362665196,
(cpg_float)0.25441145221464200876,
(cpg_float)0.79784091802427836715,
(cpg_float)0.95732389110044013858,
(cpg_float)0.84201941147054648606,
(cpg_float)0.64982839199813158260,
(cpg_float)0.62008491851713898324,
(cpg_float)0.08359122644124217238,
(cpg_float)0.96905572126736638783,
};

cpg_float canon_h_conditioning[19] = {
(cpg_float)0.00000000000000000000,
(cpg_float)0.00000000000000000000,
(cpg_float)0.00000000000000000000,
(cpg_float)0.00000000000000000000,
(cpg_float)0.00000000000000000000,
(cpg_float)0.00000000000000000000,
(cpg_float)0.00000000000000000000,
(cpg_float)29.99999000000000037858,
(cpg_float)0.75367356636115956370,
(cpg_float)0.96899350370282977263,
(cpg_float)0.04513781466362665196,
(cpg_float)0.25441145221464200876,
(cpg_float)0.79784091802427836715,
(cpg_float)0.95732389110044013858,
(cpg_float)0.84201941147054648606,
(cpg_float)0.64982839199813158260,
(cpg_float)0.62008491851713898324,
(cpg_float)0.08359122644124217238,
(cpg_float)0.96905572126736638783,
};

// Struct containing canonical parameters
Canon_Params_t Canon_Params = {
.c = (cpg_float *) &canon_c,
.d = 0.00000000000000000000,
.A = 0,
.b = 0,
.G = &canon_G,
.h = (cpg_float *) &canon_h,
};

Canon_Params_t Canon_Params_conditioning = {
.c = (cpg_float *) &canon_c_conditioning,
.d = 0.00000000000000000000,
.A = 0,
.b = 0,
.G = &canon_G_conditioning,
.h = (cpg_float *) &canon_h_conditioning,
};

// Struct containing flags for outdated canonical parameters
Canon_Outdated_t Canon_Outdated = {
.c = 1,
.d = 1,
.A = 1,
.b = 1,
.G = 1,
.h = 1,
};

// User-defined variables
cpg_float x[4] = {
(cpg_float)0.00000000000000000000,
(cpg_float)0.00000000000000000000,
(cpg_float)0.00000000000000000000,
(cpg_float)0.00000000000000000000,
};

// Struct containing primal solution
CPG_Prim_t CPG_Prim = {
.x = (cpg_float *) &x,
};

// Dual variables associated with user-defined constraints
cpg_float d0[5] = {
(cpg_float)0.00000000000000000000,
(cpg_float)0.00000000000000000000,
(cpg_float)0.00000000000000000000,
(cpg_float)0.00000000000000000000,
(cpg_float)0.00000000000000000000,
};

cpg_float d1[2] = {
(cpg_float)0.00000000000000000000,
(cpg_float)0.00000000000000000000,
};

cpg_float d2[5] = {
(cpg_float)0.00000000000000000000,
(cpg_float)0.00000000000000000000,
(cpg_float)0.00000000000000000000,
(cpg_float)0.00000000000000000000,
(cpg_float)0.00000000000000000000,
};

cpg_float d3[5] = {
(cpg_float)0.00000000000000000000,
(cpg_float)0.00000000000000000000,
(cpg_float)0.00000000000000000000,
(cpg_float)0.00000000000000000000,
(cpg_float)0.00000000000000000000,
};

// Struct containing dual solution
CPG_Dual_t CPG_Dual = {
.d0 = (cpg_float *) &d0,
.d1 = (cpg_float *) &d1,
.d2 = (cpg_float *) &d2,
.d3 = (cpg_float *) &d3,
.d4 = 0,
.d5 = 0,
};

// Struct containing solver info
CPG_Info_t CPG_Info = {
.obj_val = 0,
.iter = 0,
.status = 0,
.pri_res = 0,
.dua_res = 0,
};

// Struct containing solution and info
CPG_Result_t CPG_Result = {
.prim = &CPG_Prim,
.dual = &CPG_Dual,
.info = &CPG_Info,
};

// Struct containing solver settings
Canon_Settings_t Canon_Settings = {
.feastol = 1e-8,
.abstol = 1e-8,
.reltol = 1e-8,
.feastol_inacc = 1e-4,
.abstol_inacc = 5e-5,
.reltol_inacc = 5e-5,
.maxit = 100,
};

// ECOS array of SOC dimensions
cpg_int ecos_q[4] = {
5,
2,
5,
5,
};

// ECOS workspace
pwork* ecos_workspace = 0;

// ECOS exit flag
cpg_int ecos_flag = -99;
