
/*
Auto-generated by CVXPYgen on September 25, 2025 at 21:59:06.
Content: Function definitions.
*/

#include "cpg_solve.h"
#include "cpg_workspace.h"

static cpg_int i;
static cpg_int j;

// Update user-defined parameters
void cpg_update_b_2(cpg_float val){
  cpg_params_vec[0] = val;
  Canon_Outdated.h = 1;
}

void cpg_update_c_31(cpg_float val){
  cpg_params_vec[1] = val;
  Canon_Outdated.G = 1;
}

void cpg_update_d_3(cpg_float val){
  cpg_params_vec[2] = val;
  Canon_Outdated.h = 1;
}

void cpg_update_A_31(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+3] = val;
  Canon_Outdated.G = 1;
}

void cpg_update_b_3(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+7] = val;
  Canon_Outdated.h = 1;
}

void cpg_update_c_41(cpg_float val){
  cpg_params_vec[11] = val;
  Canon_Outdated.G = 1;
}

void cpg_update_d_4(cpg_float val){
  cpg_params_vec[12] = val;
  Canon_Outdated.h = 1;
}

void cpg_update_A_41(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+13] = val;
  Canon_Outdated.G = 1;
}

void cpg_update_b_4(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+17] = val;
  Canon_Outdated.h = 1;
}

// Map user-defined to canonical parameters
void cpg_canonicalize_G(){
  for(i=0; i<19; i++){
    Canon_Params.G->x[i] = 0;
    for(j=canon_G_map.p[i]; j<canon_G_map.p[i+1]; j++){
      Canon_Params.G->x[i] += canon_G_map.x[j]*cpg_params_vec[canon_G_map.i[j]];
    }
  }
}

void cpg_canonicalize_h(){
  for(i=0; i<19; i++){
    Canon_Params.h[i] = 0;
    for(j=canon_h_map.p[i]; j<canon_h_map.p[i+1]; j++){
      Canon_Params.h[i] += canon_h_map.x[j]*cpg_params_vec[canon_h_map.i[j]];
    }
  }
}

// Retrieve primal solution in terms of user-defined variables
void cpg_retrieve_prim(){
  CPG_Prim.x[0] = ecos_workspace->x[0];
  CPG_Prim.x[1] = ecos_workspace->x[1];
  CPG_Prim.x[2] = ecos_workspace->x[2];
  CPG_Prim.x[3] = ecos_workspace->x[3];
}

// Retrieve dual solution in terms of user-defined constraints
void cpg_retrieve_dual(){
  CPG_Dual.d0[0] = ecos_workspace->z[2];
  CPG_Dual.d0[1] = ecos_workspace->z[3];
  CPG_Dual.d0[2] = ecos_workspace->z[4];
  CPG_Dual.d0[3] = ecos_workspace->z[5];
  CPG_Dual.d0[4] = ecos_workspace->z[6];
  CPG_Dual.d1[0] = ecos_workspace->z[7];
  CPG_Dual.d1[1] = ecos_workspace->z[8];
  CPG_Dual.d2[0] = ecos_workspace->z[9];
  CPG_Dual.d2[1] = ecos_workspace->z[10];
  CPG_Dual.d2[2] = ecos_workspace->z[11];
  CPG_Dual.d2[3] = ecos_workspace->z[12];
  CPG_Dual.d2[4] = ecos_workspace->z[13];
  CPG_Dual.d3[0] = ecos_workspace->z[14];
  CPG_Dual.d3[1] = ecos_workspace->z[15];
  CPG_Dual.d3[2] = ecos_workspace->z[16];
  CPG_Dual.d3[3] = ecos_workspace->z[17];
  CPG_Dual.d3[4] = ecos_workspace->z[18];
  CPG_Dual.d4 = ecos_workspace->z[0];
  CPG_Dual.d5 = ecos_workspace->z[1];
}

// Retrieve solver info
void cpg_retrieve_info(){
  CPG_Info.obj_val = (ecos_workspace->info->pcost);
  CPG_Info.iter = ecos_workspace->info->iter;
  CPG_Info.status = ecos_flag;
  CPG_Info.pri_res = ecos_workspace->info->pres;
  CPG_Info.dua_res = ecos_workspace->info->dres;
}

// Copy canonical parameters for preconditioning
void cpg_copy_c(){
  for (i=0; i<4; i++){
    Canon_Params_conditioning.c[i] = Canon_Params.c[i];
  }
}

void cpg_copy_A(){
}

void cpg_copy_b(){
}

void cpg_copy_G(){
  for (i=0; i<19; i++){
    Canon_Params_conditioning.G->x[i] = Canon_Params.G->x[i];
  }
}

void cpg_copy_h(){
  for (i=0; i<19; i++){
    Canon_Params_conditioning.h[i] = Canon_Params.h[i];
  }
}

void cpg_copy_all(){
  cpg_copy_c();
  cpg_copy_A();
  cpg_copy_b();
  cpg_copy_G();
  cpg_copy_h();
}

// Solve via canonicalization, canonical solve, retrieval
void cpg_solve(){
  // Canonicalize if necessary
  if (Canon_Outdated.G) {
    cpg_canonicalize_G();
  }
  if (Canon_Outdated.h) {
    cpg_canonicalize_h();
  }
  if (!ecos_workspace ) {
    cpg_copy_all();
    ecos_workspace = ECOS_setup(4, 19, 0, 2, 4, (int *) &ecos_q, 0, Canon_Params_conditioning.G->x, Canon_Params_conditioning.G->p, Canon_Params_conditioning.G->i, 0, 0, 0, Canon_Params_conditioning.c, Canon_Params_conditioning.h, 0);
  } else {
    if (Canon_Outdated.A || Canon_Outdated.b || Canon_Outdated.G) {
      cpg_copy_all();
      ECOS_updateData(ecos_workspace, Canon_Params_conditioning.G->x, 0, Canon_Params_conditioning.c, Canon_Params_conditioning.h, 0);
    } else {
      if (Canon_Outdated.h) {
        cpg_copy_h();
        for (i=0; i<19; i++) { ecos_updateDataEntry_h(ecos_workspace, i, Canon_Params_conditioning.h[i]); };
      }
    }
  }
  ecos_workspace->stgs->feastol = Canon_Settings.feastol;
  ecos_workspace->stgs->abstol = Canon_Settings.abstol;
  ecos_workspace->stgs->reltol = Canon_Settings.reltol;
  ecos_workspace->stgs->feastol_inacc = Canon_Settings.feastol_inacc;
  ecos_workspace->stgs->abstol_inacc = Canon_Settings.abstol_inacc;
  ecos_workspace->stgs->reltol_inacc = Canon_Settings.reltol_inacc;
  ecos_workspace->stgs->maxit = Canon_Settings.maxit;
  // Solve with ECOS
  ecos_flag = ECOS_solve(ecos_workspace);
  // Retrieve results
  cpg_retrieve_prim();
  cpg_retrieve_dual();
  cpg_retrieve_info();
  // Reset flags for outdated canonical parameters
  Canon_Outdated.G = 0;
  Canon_Outdated.h = 0;
}

// Update solver settings
void cpg_set_solver_default_settings(){
  Canon_Settings.feastol = 1e-8;
  Canon_Settings.abstol = 1e-8;
  Canon_Settings.reltol = 1e-8;
  Canon_Settings.feastol_inacc = 1e-4;
  Canon_Settings.abstol_inacc = 5e-5;
  Canon_Settings.reltol_inacc = 5e-5;
  Canon_Settings.maxit = 100;
}

void cpg_set_solver_feastol(cpg_float feastol_new){
  Canon_Settings.feastol = feastol_new;
}

void cpg_set_solver_abstol(cpg_float abstol_new){
  Canon_Settings.abstol = abstol_new;
}

void cpg_set_solver_reltol(cpg_float reltol_new){
  Canon_Settings.reltol = reltol_new;
}

void cpg_set_solver_feastol_inacc(cpg_float feastol_inacc_new){
  Canon_Settings.feastol_inacc = feastol_inacc_new;
}

void cpg_set_solver_abstol_inacc(cpg_float abstol_inacc_new){
  Canon_Settings.abstol_inacc = abstol_inacc_new;
}

void cpg_set_solver_reltol_inacc(cpg_float reltol_inacc_new){
  Canon_Settings.reltol_inacc = reltol_inacc_new;
}

void cpg_set_solver_maxit(cpg_int maxit_new){
  Canon_Settings.maxit = maxit_new;
}
